---
language: python

python:
- '2.7'

services:
- docker

install:
- curl -O https://raw.githubusercontent.com/systemslab/popperci/master/implementations/python/docker/entrypoint.py
- chmod 755 entrypoint.py

script: ./entrypoint.py
